<div class="container"></div>

<script type="text/javascript">
        function Busqueda(){
             var segundos = 1;
            segundos = segundos * 1000;
            var consulta;
                     consulta = $("#busqueda").val();                               
                   // $("#resultado").html("<img src='/img/cargando.gif'> Cargando...");                             
                           $.ajax({
                               type: "POST",
                               url: "/admin/alumno/busqueda",
                               data: "b="+consulta,
                               dataType: "html",
                               beforeSend: function(){
                                  $("#resultado").html("<p align='center'><img src='/img/cargando.gif' /></p>");
                                 // 
                               },
                               error: function(){
                                       alert("error petición ajax");
                                 },
                               success: function(data){ 
                                  // alert(data);
                                   $("#resultado").html(data)  
                                       n();
                                 }
                                 
                            });
      }
  $(document).ready(function(){
      var segundos = 2;
      segundos = segundos * 1000;
      $("#busqueda").focus();
                                                                          
});
    
</script>
<div class="container">
    

   

    <div class="row ">
        <div class="span4">    
     <fieldset>
        <center>
            <legend>Busqueda de Alumno</legend>
        </center>             
    </fieldset></div>
     
        <div class="span4" >
            
        </div>
        <div class="span4">
            <div class="form-search" >
                <div class="input-prepend">
                    <div class="control-group success">
                    <button type="button"  onclick="Busqueda();" class="btn btn-success">Buscar</button>
                    <input type="text" class="span2 search-query" id="busqueda">
                    </div>
                </div>
            </div>
        </div>     
    </div> 


<div class="container" id="resultado"></div>   

</div>
