<script type="text/javascript">
      $(function() {
      $( "#fec_na" || "#inicio" ).datepicker({ 
          appendText: "(yyyy-mm-dd)",
          dateFormat: "yy-mm-dd",
           //changeMonth: true,
           //changeYear: true,
          dayNames: [ "Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" ],
          dayNamesMin: [ "Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa" ],
          monthNames: [ "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Dicimbre" ],
          duration: "slow",
          showAnim: "slideDown"});   
    
  });
</script>
<div class="container">
    <fieldset>
        <center>
            <legend>Editar Alumno</legend>
        </center>  
    </fieldset>
<?php echo $this->form;?>
</div>  
