<div class="row">
    <div class="span2"></div>
    <div class="span8">
        <h3 class="text-center">Bienvenido al SAP</h3>

<p>Sistema de administracion y publicacion en linea (SAP) del la escuela de terapia fisica del DIF  Chiapas</p>
<h4>El sistema le proporciona las siguientes opciones:</h4>
<p>
    <strong>Grupos Asignados</strong>:En esta opcion encontrara a todos los grupos  que se le asignado
    en ciclo escolares anteriores como actuales. 
    
    
</p>
</div>
    <div class="span2"></div>
</div>