<form class="form-horizontal" method="post" name="form">

            <div class="form-search" >
                <div class="input-prepend">
                    <div class="control-group success">
                   <button type="submit" class="btn btn-success">Aceptar</button>
                        <?php echo $this->element->getElement('baja');?>
                    </div>
                </div>
            </div>
       
    </form>

