<!Doctype html>
<html>
    <head>
        <title>RecuperarContraseña</title>
        <meta charset="UTF-8" />
        <link href="/css/bootstrap.css" rel="stylesheet" type="text/css">
        <link href="/css/estilos.css" rel="stylesheet">
        <link  href="/css/bootstrap-responsive.css" rel="STYLESHEET" type="text/css" >
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="span3"></div>
            <div class="span6">
                <h3 class="text-center text-info"> Recuperacion de contraseñas</h3>
                
                <?php echo   $this->form;?>
                  <?php if ( isset($this->error) ) {
                    echo $this->error;
                    
                   } ?>
         </div>
                <div class="span3"></div>
         </div>
         </div>
    </body>
</html>





