<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Menu Alumno</title>
        <meta charset="utf-8">
        <link  href="/css/bootstrap.css" rel="STYLESHEET" type="text/css" >
        <link  href="/css/bootstrap-responsive.css" rel="STYLESHEET" type="text/css">
        <link  href="/css/estilos.css" rel="STYLESHEET" type="text/css" > 
        <script src="/js/jquery-1.9.1.js"></script>
        <script src="/js/jquery.validate.js" type="text/javascript"></script>
        <script src="/js/bootstrap-dropdown.js"></script>
        <link rel="shortcut icon" href="/img/logo.ico">
        
        <?php
        $auth=Zend_Auth::getInstance(); 
        $usuario=$auth->getStorage()->read();
      
        ?>
    </head>
    <body>
    <div class="container">
        
    <img src="/img/alumno.png">
              
            
    <div class="navbar navbar-inverse">
    <div class="navbar-inner">
    <div class="container">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
 
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
    <a class="brand" href="#">Bienvenido:<?php echo $usuario->numcontrol;?></a>
     
    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
        <ul class="nav navbar-inverse">
                      
                        
                                <li class="divider-vertical"></li>
                                <li><a href="/alu/kardex/index">Ver Kardex</a></li>
                                <li class="divider-vertical"></li>
                                <li><a href="/alu/kardex/boleta">Boleta</a></li>
                                <li class="divider-vertical"></li>
                                <li><a href="/alu/horario/index">Cal. parciales</a></li>
                                <li class="divider-vertical"></li>
                                <li><a href="/alu/datos/index">Datos Personales</a></li>
                                <li class="divider-vertical"></li>
                                <li><a href="/alu/datos/cambiarclave" >Cambiar contraseña</a></li>
                                <li class="divider-vertical"></li>
                                <li ><a href="/alu/datos/cerrarsesion">Cerrar sesion</a></li>
                                <li class="divider-vertical"></li>
                    </ul> 
              
        
   
    </div>
     
    </div>
    </div>
    </div>
    <hr>
            
            <div class="row">
                <div class="span12">
                <?php echo $this->layout()->content; ?>
                </div>
                </div>
  </div>
    </body>
</html>
                                        
                                    
       