<h3 class="text-center text-info">Grupos Asignados</h3>
<div class="row">
    <div class="span3">
        <div class="span1"></div>
        <div class="span2">
           <?php echo  $this->form; ?> 
        </div>
            
    </div>
    <div class="span8">
        <h5 class="text-success">Grupos Asignados en el ciclo:  <strong><?php echo $this->periodo; ?></strong></h5>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><small>Grupo</small></th>
                    <th><small>Clave</small></th>
                    <th><small>Asignatura</small></th>
                    <th><small>Opciones</small></th>
                </tr>
            </thead>
            
            <?php  if(count($this->grupos)):?>
            <tbody>
                <?php foreach ($this->grupos as $grupo):?>
                <tr class="text-info">
                    <td><?php echo $grupo->idgrupo ?></td>
                    <td><?php echo $grupo->clavemateria ?></td>
                    <td><small><?php echo $grupo->materia ?></small></td>
                    <td><a href="/prof/grupos/imprimir/idgrupo/<?php echo $grupo->idgrupo; ?>">Imprimir<i class="icon-print"></i></a></td>
                    <?php if ($grupo->capturar!=1): ?>
                    <td class="btn-small"><a href="/prof/grupos/capturar/idgrupo/<?php echo $grupo->idgrupo; ?>"><abbr class="initialism" title="Asignar calificaciones"><small>Capturar</small></abbr></a></td>
                   <?php endif; ?> 
                </tr>
                <?php endforeach;?>        
     
            
            <?php endif;?>
            </tbody>
        </table>
        
        
        
    </div>
    <div class="span1"></div>
    
 </div>

 